# Generated by Django 5.1.2 on 2024-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_image", models.ImageField(upload_to="")),
                ("header_title", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
