# Generated by Django 5.1.2 on 2024-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="chair_message",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpage",
            name="chair_name",
            field=models.CharField(default="hello", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpage",
            name="chair_photo",
            field=models.ImageField(default="h", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpage",
            name="welcome_statement",
            field=models.TextField(default="h"),
            preserve_default=False,
        ),
    ]
