# Generated by Django 5.1.2 on 2024-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_mainpage_chair_message_mainpage_chair_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="chair_signature",
            field=models.ImageField(default="h", upload_to=""),
            preserve_default=False,
        ),
    ]
