# Generated by Django 5.1.2 on 2024-12-04 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_mainpage_chair_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage",
            name="chair_message",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="welcome_statement",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
