# Generated by Django 5.1.2 on 2024-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_mainpage_chair_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage",
            name="chair_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="chair_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="chair_signature",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="header_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
