# Generated by Django 5.1.2 on 2024-12-05 19:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Latest", "Latest"), ("Upcoming", "Upcoming")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
