# Generated by Django 5.1.2 on 2025-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_options_alter_news_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("header_image", models.ImageField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
