# Generated by Django 5.1.2 on 2025-05-14 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newspageconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="header_image",
        ),
    ]
