# Generated by Django 5.1.2 on 2025-05-14 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_news_header_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="title",
        ),
    ]
