# Generated by Django 5.1.2 on 2024-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="name",
            field=models.CharField(default="rwe", max_length=200),
            preserve_default=False,
        ),
    ]
