# Generated by Django 5.1.2 on 2024-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0003_alter_block_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="main_description",
            field=models.TextField(default="program desc"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="main_name",
            field=models.CharField(default="desc", max_length=200),
            preserve_default=False,
        ),
    ]
