# Generated by Django 5.1.2 on 2024-12-05 19:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0004_program_main_description_program_main_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="main_description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="program",
            name="main_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
