# Generated by Django 5.1.2 on 2025-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0005_alter_block_text_alter_link_link_alter_link_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="main_image",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
