# Generated by Django 5.1.2 on 2025-05-11 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0006_program_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="main_image",
        ),
    ]
