# Generated by Django 5.1.2 on 2025-05-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0007_remove_program_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="main_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
