# Generated by Django 5.1.2 on 2025-05-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="speaker_link",
            field=models.URLField(blank=True),
        ),
    ]
