# Generated by Django 5.1.2 on 2025-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_date_alter_event_speaker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="header_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
