# Generated by Django 5.1.2 on 2024-11-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("position", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("room_number", models.CharField(max_length=50)),
                (
                    "curriculum_vitae",
                    models.FileField(blank=True, null=True, upload_to="cv/"),
                ),
                ("photo", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("PhD", "Ph.D"),
                            ("MS", "M.S."),
                            ("BS", "B.S."),
                            ("BA", "B.A."),
                            ("MBA", "M.B.A."),
                            ("MA", "M.A."),
                            ("MD", "M.D."),
                            ("JD", "J.D."),
                            ("DVM", "D.V.M."),
                        ],
                        max_length=10,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("year_awarded", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="staff.staffmember",
                    ),
                ),
            ],
        ),
    ]
