# Generated by Django 5.1.2 on 2024-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staffpageconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffmember",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="staffmember",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
