# Generated by Django 5.1.2 on 2024-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_alter_staffmember_options_staffmember_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="year_awarded",
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
