# Generated by Django 5.1.2 on 2025-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_remove_education_year_awarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpageconfig",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
